### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by nkusongzhichao** [HIRO-group/HIRO_Panda_TRAC_IK#1]
![error](https://user-images.githubusercontent.com/45937564/102436024-a1bdd280-4052-11eb-8435-fd28b1da7ec0.png)
Hi, sorry to trouble you.

I have one problem when I run ``catkin build``

**Comment by peasant98** [comment]
Hi @nkusongzhichao, looks like you'll need to install the ROS packages here: `https://github.com/frankaemika/franka_ros`

**Comment by peasant98** [comment]
I'll elaborate -- you'll need to go through https://frankaemika.github.io/docs/installation_linux.html. My bad for not putting this in the readme -- I'll do so now.

**Comment by nkusongzhichao** [comment]
> Hi @nkusongzhichao, looks like you'll need to install the ROS packages here: `https://github.com/frankaemika/franka_ros`

Thank you for your reply!!  I had installed the ROS packages and I can run the demo with the real panda robot. Maybe it doesn't find its path?

**Comment by peasant98** [comment]
Try the command, `rospack list | grep franka_control`. What do you get?

**Comment by nkusongzhichao** [comment]
![131231](https://user-images.githubusercontent.com/45937564/102437626-cd8e8780-4055-11eb-9b97-aa73c1336d6a.png)
I can't find the ``franka_control``. Just find these results..

**Comment by nkusongzhichao** [comment]
> Try the command, `rospack list | grep franka_control`. What do you get?

Thank you for your help. I'm sorry. I try to install ``franka_ros``  by  ``apt`` and compiled it successfully.

**Comment by peasant98** [comment]
Ah I see. @nkusongzhichao in that case, I would check out these steps: https://frankaemika.github.io/docs/installation_linux.html

If you only need to install the `franka_ros` related packages, you can try:

```sh
sudo apt install ros-melodic-libfranka ros-melodic-franka-ros
```

**Comment by peasant98** [comment]
Ah did it work @nkusongzhichao?

**Comment by nkusongzhichao** [comment]
> Ah did it work @nkusongzhichao?

Yes, it work!

**Comment by peasant98** [comment]
Ah great!

**Comment by nkusongzhichao** [comment]
> Ah great!

Hah, thank you a lot.~~

**Comment by peasant98** [comment]
If it all worked, I can close this issue.

**Comment by nkusongzhichao** [comment]
> If it all worked, I can close this issue.

OK~~~

**Comment by peasant98** [comment]
Cool, thanks @nkusongzhichao for pointing this out!
